//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHomeWork.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Threading.Tasks;
    using System.ComponentModel;

    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        [DisplayName ("客戶名稱")]
        public int 客戶Id { get; set; }
        [Required(ErrorMessage = "職稱不可空白")]
        public string 職稱 { get; set; }
        [Required(ErrorMessage = "姓名不可空白")]
        public string 姓名 { get; set; }

        [Required(ErrorMessage = "Email不可空白")]
        [EmailAddress(ErrorMessage = "請輸入正確的Email")]

        [Remote("檢查Email是否存在", "客戶聯絡人", AdditionalFields = "Email,客戶Id", ErrorMessage = "該Email已存在")]
        public string Email { get; set; }

        [RegularExpression(@"^\d{4}-\d{6}$",  ErrorMessage = "手機電話格式必須為0911-111111")]
        public string 手機 { get; set; }
        public string 電話 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }

        internal Task<object> FindByNameAsync(string email)
        {
            throw new NotImplementedException();
        }
    }

}
